### PR TITLE
Azure AION deployment code review

### PR DESCRIPTION
**Pull request by radhikabhat08**
Request review

---
This change is [Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1)

### CODE REVIEW

**Comment by radhikabhat08** [comment]
___
*[examples/run-aion/main.tf, line 2 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSYQgsC9ABJtVJxYtdp:-MSYQgsC9ABJtVJxYtdq:b-gjhhj1) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/examples/run-aion/main.tf#L2)):*
> ```HCL
> ## Example : This Terraform module deploys Spirent TestCenter Virtual Machines from an Azure Marketplace image.
> # The example requires the user to provide an already existing virtual network , management subnet, test subnet names.
> ```

missed removing this part, will take care in next commit along with other changes requested.

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[main.tf, line 8 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ2mMO9wbj7teqhx9x:-MSZ2mMO9wbj7teqhx9y:bcm5gbg) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/main.tf#L8)):*
> ```HCL
> 
> resource "azurerm_network_security_group" "mgmt_plane" {
>   
> ```

remove whitespace chars (multiple occurrences).  please configure your editor to display whitespace chars to avoid this from happening in the future.

check other files in this PR as well.
___
*[main.tf, line 78 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ3yFX-t0tw_VZA4rB:-MSZ3yFX-t0tw_VZA4rC:ba0lkxs) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/main.tf#L78)):*
> ```HCL
>     direction                  = "Inbound"
>     access                     = "Allow"
>     protocol                   = "icmp"
> ```

As-is, this block and the `icmp` security rule block above are identical.

Does Azure support a separate `icmp6` protocol enum?  If not, is IPv6 handled through the `source_address_prefixes`?
___
*[variables.tf, line 45 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ5XOW2_bykzVKKoRN:-MSZ5XOW2_bykzVKKoRO:b-rjs2j2) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L45)):*
> ```HCL
> 
> variable "enable_provisioner" {
>   description = "Enable provisioning"
> ```

Needs more description.  Please copy/paste from the AWS AION variables.tf description.
___
*[variables.tf, line 90 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ5tdg5e7fKn3WdbXc:-MSZ5tdg5e7fKn3WdbXd:br5l97a) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L90)):*
> ```HCL
> 
> variable "admin_password" {
>   description = "Cluster admin user password. Use this to login to to the instance web page."
> ```

remove one `to`
___
*[variables.tf, line 137 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ5jWh0wsI1M7N3a6y:-MSZ5jWh0wsI1M7N3a6z:b-t1pq1r) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L137)):*
> ```HCL
> 
> variable "dest_dir" {
>   description = "Destination directory on the instance where provisining files will be copied"
> ```

provisining -> provisioning

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1)* status: 8 of 9 files reviewed, 7 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

___
*[variables.tf, line 36 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZPFiP7J0fkLAMpFw7:-MSZPFiQ6Y8hTOIcRb1a:bsfhrmw) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L36)):*
> ```HCL
>   description = "VNET name in Azure"
>   default     = ""
> }
> ```

I noticed virtual_network_name variable in the stcv module too.  It doesn't seem to be getting used in the module,  Only in the example.  I think we should remove it.  Can you remove it here?  I'm going to submit a PR for STCv.

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1)* status: 4 of 9 files reviewed, 7 unresolved discussions (waiting on @jhiga, @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[main.tf, line 8 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ2mMO9wbj7teqhx9x:-MS_JBl03Ce1ft-dBnE3:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/main.tf#L8)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

remove whitespace chars (multiple occurrences).  please configure your editor to display whitespace chars to avoid this from happening in the future.

check other files in this PR as well.
</blockquote></details>

Done.
___
*[variables.tf, line 36 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZPFiP7J0fkLAMpFw7:-MSbP-rq0KcoLvWj_flP:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L36)):*
<details><summary><i>Previously, rmyers808 (Richard Myers) wrote…</i></summary><blockquote>

I noticed virtual_network_name variable in the stcv module too.  It doesn't seem to be getting used in the module,  Only in the example.  I think we should remove it.  Can you remove it here?  I'm going to submit a PR for STCv.   
</blockquote></details>

Done.
___
*[variables.tf, line 45 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ5XOW2_bykzVKKoRN:-MS_LYKbEpw5offBCo5X:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L45)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Needs more description.  Please copy/paste from the AWS AION variables.tf description.
</blockquote></details>

Done.
___
*[variables.tf, line 90 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ5tdg5e7fKn3WdbXc:-MS_Lea27dajw1C0aUHU:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L90)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

remove one `to`
</blockquote></details>

Done.
___
*[variables.tf, line 137 at r1](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSZ5jWh0wsI1M7N3a6y:-MS_Ljn96dUlqhKOAuon:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/d9d4f4cf890b1e4b2575ed4d106ef5f5ea8c3397/variables.tf#L137)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

provisining -> provisioning
</blockquote></details>

Done.

**Review by jhiga — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1)* status: all files reviewed, 3 unresolved discussions (waiting on @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[main.tf, line 2 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MScko1u4HH8qsIxG9dv:-MScko1u4HH8qsIxG9dw:b-4s78d1) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/3bdf47f52cca33ab5a453efe77e9283b48498772/main.tf#L2)):*
> ```HCL
> provider "azurerm" {
>   version                    = ">=2.37.0"
> ```

Consider moving version constraints to `version.tf` per Richard's [PR](https://github.com/Spirent-Terraform-Modules/terraform-aws-stcv/pull/3/files#diff-e5d10353ef4096b7bca871749a46c72a51a1fb47f0049bcdd72bdc8c858509e7).

**Review by radhikabhat08 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1)* status: 4 of 13 files reviewed, 3 unresolved discussions (waiting on @jhiga, @ltran-spirent, and @rmyers808)

___
*[main.tf, line 2 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MScko1u4HH8qsIxG9dv:-MSnR0fW-wWFZbV28qF9:b-896fix) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/3bdf47f52cca33ab5a453efe77e9283b48498772/main.tf#L2)):*
<details><summary><i>Previously, jhiga (Justin Higa) wrote…</i></summary><blockquote>

Consider moving version constraints to `version.tf` per Richard's [PR](https://github.com/Spirent-Terraform-Modules/terraform-aws-stcv/pull/3/files#diff-e5d10353ef4096b7bca871749a46c72a51a1fb47f0049bcdd72bdc8c858509e7).
</blockquote></details>

Done.

**Review by rmyers808 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 3 of 5 files at r2, 2 of 2 files at r3, 2 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1)* status: 6 of 13 files reviewed, 3 unresolved discussions (waiting on @jhiga, @ltran-spirent, @radhikabhat08, and @rmyers808)

___
*[main.tf, line 2 at r3](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MScko1u4HH8qsIxG9dv:-MSvGPRx9XXnZyJedVsa:b71oa3i) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/3bdf47f52cca33ab5a453efe77e9283b48498772/main.tf#L2)):*
<details><summary><i>Previously, radhikabhat08 (radhika bhat) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think this give a warning?  You should remove "azurerm" completely from the man.tf file.  In the examples it's okay to have azurerm but remove  "version"
___
*[version.tf, line 2 at r4](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-MSvHKO29B_-5iQsGbYD:-MSvHKO29B_-5iQsGbYE:b-aq92c6) ([raw file](https://github.com/spirent-terraform-modules/terraform-azurerm-aion/blob/fee4ac216d40a73ac25f73b21d0f6cf08e6dfd89/version.tf#L2)):*
> ```HCL
> terraform  {
>   required_version = ">= 0.13.0"
> ```

Should put this block in terraform:  
  required_providers {
    azurerm = ">=2.37.0"
  }

See this file:  https://github.com/Spirent-Terraform-Modules/terraform-azurerm-stcv/blob/d51d2dabb226de2ff57400750b5f84ac196fc9b5/version.tf#L4

**Review by jhiga — APPROVED** [review]
:lgtm:

> Reviewed 8 of 9 files at r4, 1 of 1 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/spirent-terraform-modules/terraform-azurerm-aion/1#-:-MT-64301xQ8ok5570V2:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ltran-spirent and @radhikabhat08)

**Review by rmyers808 — APPROVED** [review]

**Pull request merged**
